export const zeroProposalStyles = `
*{box-sizing:border-box;letter-spacing:0}
html{scroll-behavior:smooth;scroll-padding-top:28px}
body{margin:0;background:#fff;color:#242628;font:16px/1.65 Arial,Helvetica,sans-serif;overflow-wrap:anywhere}
h1,h2,h3,p,figure{margin:0}h1,h2{font-family:var(--display);font-weight:var(--weight);line-height:1.12;text-wrap:balance}
h1{font-size:76px;max-width:960px}h1.long-title{font-size:48px}h2{font-size:44px}h3{font-size:24px;line-height:1.3;font-weight:600}
a{color:inherit;text-decoration:none}a:focus-visible,summary:focus-visible{outline:3px solid var(--accent);outline-offset:5px}
p+p{margin-top:14px}img{display:block;max-width:100%}.wrap{width:min(1120px,88%);margin-inline:auto}
.brandbar{min-height:82px;display:flex;align-items:center;justify-content:space-between;gap:24px;padding-block:20px}
.brandbar .brand{max-width:50%;font-size:20px;font-weight:700;line-height:1.3}
.brandbar img{width:150px;max-height:44px;object-fit:contain;object-position:left}
.brandbar nav{display:flex;gap:24px;font-size:14px;color:#626568}.brandbar nav a:hover{color:var(--ink)}
.hero{position:relative;isolation:isolate;min-height:min(610px,calc(100svh - 190px));display:flex;align-items:flex-end;padding-block:100px 58px;color:#fff;background:#252a30}
.hero-media{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;z-index:-2}
.hero:before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(7,13,19,.9),rgba(7,13,19,.56) 45%,rgba(7,13,19,.2)),linear-gradient(180deg,rgba(9,15,22,.08),rgba(9,15,22,.78));z-index:-1}
.hero-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,360px);align-items:end;gap:42px}
.hero-copy{position:relative;text-shadow:0 2px 16px #0005}
.eyebrow{display:block;font-size:13px;text-transform:uppercase;margin-bottom:20px}
.hero-subject{font-size:23px;line-height:1.5;max-width:760px;margin-top:20px;text-wrap:balance}
.hero-link{display:inline-flex;align-items:center;gap:24px;font-size:14px;border-bottom:1px solid #ffffff80;padding-bottom:8px;margin-top:30px}
.hero-edition{position:absolute;top:28px;right:6%;font-size:12px;color:#fff}
.hero-card{position:relative;min-width:0;padding:28px;border:1px solid #ffffff38;border-radius:8px;background:rgba(255,255,255,.13);backdrop-filter:blur(16px);box-shadow:0 24px 70px #00000030;text-shadow:none}
.hero-card:before{content:'';display:block;width:42px;height:3px;background:var(--accent);margin-bottom:28px}
.hero-card span{display:block;font-size:12px;text-transform:uppercase;color:#ffffffb8;margin-bottom:10px}.hero-card strong{display:block;font:var(--weight) 32px/1.08 var(--display);overflow-wrap:anywhere}.hero-card p{margin-top:18px;color:#ffffffe0}.hero-card small{display:inline-flex;margin-top:22px;border-radius:24px;background:var(--accent);color:var(--on-accent);padding:10px 14px;font-size:13px;font-weight:700}
.project-strip{border-bottom:1px solid #e5e7e9;background:#fff}
.project-facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,180px),1fr));gap:20px;margin:0;padding-block:28px}
.project-facts dt{font-size:12px;color:#6b7175;margin-bottom:6px}.project-facts dd{margin:0;font-size:16px;font-weight:600;line-height:1.4}
.section{padding-block:80px}.section-label{display:block;text-transform:uppercase;font-size:12px;color:var(--ink);font-weight:600;margin-bottom:18px}
.section-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:40px}
.section-heading>span{font-size:13px;color:#686d70;flex-shrink:0}
.context{border-bottom:1px solid #e5e7e9}.objective-copy{font:var(--weight) 32px/1.5 var(--display);max-width:900px;text-wrap:pretty;white-space:pre-wrap}.objective-copy.long-copy{font:400 18px/1.85 Arial,sans-serif}
.insight-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:18px;margin-top:42px}
.insight-grid article{position:relative;min-width:0;border:1px solid #dfe5e9;background:#fff;border-radius:8px;padding:24px;break-inside:avoid}
.insight-grid article>span{display:block;width:42px;height:3px;background:var(--accent);margin-bottom:24px}
.insight-grid h3{font-size:20px;margin-bottom:12px}.insight-grid p{color:#566066;line-height:1.7}
.scope-signals{display:grid;grid-template-columns:minmax(160px,.45fr) minmax(0,1fr);gap:28px;margin-top:34px;border-top:1px solid #d7dee3;padding-top:24px}
.scope-signals strong{font:var(--weight) 24px/1.25 var(--display);color:#202429}.scope-signals ul{list-style:none;margin:0;padding:0;display:grid;gap:10px}
.scope-signals li{display:grid;grid-template-columns:minmax(120px,.35fr) minmax(0,1fr);gap:16px;padding:12px 0;border-bottom:1px solid #e6eaee;color:#4f5961}.scope-signals li span{font-size:12px;text-transform:uppercase;color:var(--ink);font-weight:700}
.scope-chapters{border-top:1px solid #cdd3d6}.scope-chapter{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:56px;padding-block:36px;border-bottom:1px solid #dfe3e6;break-inside:avoid}
.chapter-title{display:flex;gap:28px;align-items:flex-start}.service-number{font-size:42px;line-height:1;color:var(--ink);font-family:var(--display);flex-shrink:0}
.service-type{display:block;font-size:12px;color:#6b7175;margin-bottom:12px}.chapter-title h3{font:var(--weight) 30px/1.25 var(--display)}
.chapter-content{display:flex;flex-direction:column;justify-content:space-between;align-items:flex-start;gap:24px;min-width:0}
.deliverables{list-style:none;margin:0;padding:0;color:#50565b;white-space:pre-wrap}
.deliverables li{padding:10px 0 10px 18px;position:relative;border-bottom:1px solid #e8ebed;line-height:1.65}
.deliverables li:before{content:'+';position:absolute;left:0;color:var(--ink);font-weight:600}
.deliverables li:first-child{padding-top:0}.deliverables li:last-child{border-bottom:0}
.service-outcome{margin:0 0 18px;color:#20262b;font-weight:650;line-height:1.55;text-wrap:pretty}
.service-price strong{display:block;font-size:22px;font-weight:500;font-variant-numeric:tabular-nums}.service-price>span{display:block;font-size:12px;color:#6b7175;margin-top:4px}
.schedule{background:#f4f6f7}.process{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:32px}
.process li{position:relative;min-width:0;break-inside:avoid;border-top:1px solid #b8c2c8;padding-top:24px}.step-number{display:grid;place-items:center;width:44px;height:44px;border-radius:50%;background:var(--accent);color:var(--on-accent);font-size:14px;margin-bottom:24px}
.process h3{font-size:20px;margin-bottom:12px}.process p{color:#50565b;white-space:pre-wrap}.process.single{grid-template-columns:1fr;max-width:860px}
.process.method li{background:#fff;border:1px solid #dfe5ea;border-top:4px solid var(--accent);border-radius:8px;padding:22px}
.process.method .step-number{background:#f2f5f7;color:#23313a}
.portfolio{display:grid;grid-template-columns:1fr 1fr;gap:28px}.portfolio figure{min-width:0;break-inside:avoid}.portfolio figure:first-child:nth-last-child(odd){grid-column:1/-1}
.portfolio img{width:100%;aspect-ratio:4/3;object-fit:contain;background:#f3f5f7;border-radius:8px}.portfolio figcaption{font-size:14px;padding-top:12px;color:#60686d}
.investment{background:#f1f4f7;border-block:1px solid #e1e6eb}.investment-wrap{display:grid;gap:28px}.investment-feature{display:grid;grid-template-columns:minmax(0,1fr) minmax(210px,.42fr);gap:28px;align-items:end;padding:32px;border-radius:8px;background:#fff;border:1px solid #dfe6ed;box-shadow:0 18px 44px #23384f0b}.investment-feature span{display:block;font-size:12px;text-transform:uppercase;color:var(--ink);font-weight:700;margin-bottom:12px}.investment-feature h3{font:var(--weight) 34px/1.12 var(--display);margin-bottom:14px}.investment-feature p{max-width:650px;color:#56616a}.investment-feature strong{display:block;text-align:right;font:var(--weight) 42px/1.04 var(--display);font-variant-numeric:tabular-nums;color:var(--ink)}.totals{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,230px),1fr));gap:32px}
.total{border-top:2px solid var(--accent);padding-top:20px;min-width:0}.total>span{display:block;font-size:14px;color:#555f68}.total strong{font-size:40px;line-height:1.2;font-weight:500;display:block;margin-top:16px;font-variant-numeric:tabular-nums}.total small{display:block;margin-top:8px;color:#626b73;font-size:13px}
.investment-note{font-size:14px;color:#4a555e;margin-top:24px;max-width:900px}.price-detail{margin-top:36px;padding-top:20px;border-top:1px solid #cbd4dc}.price-detail summary{cursor:pointer;font-size:14px;font-weight:600;padding:8px 0}
.table-wrap{overflow:auto;margin-top:14px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:16px 8px;border-bottom:1px solid #d7dfe6}th{font-size:12px;font-weight:500;color:#626b73}th:last-child,td:last-child{text-align:right}td:first-child{min-width:160px}
.conditions{display:grid;grid-template-columns:1fr 1fr;gap:48px}.conditions>div{border-top:1px solid #ced6dc;padding-top:24px}.conditions h3{font-size:20px;margin-bottom:18px}.conditions p{color:#50565b;white-space:pre-wrap}
.next-steps{background:#fff}.next-board{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}
.next-board article{border:1px solid #dfe5ea;border-radius:8px;padding:24px;background:linear-gradient(180deg,#fff,#f7f9fb);min-width:0;break-inside:avoid}
.next-board strong{display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:var(--accent);color:var(--on-accent);font-size:14px;margin-bottom:22px}
.next-board h3{font-size:20px;margin-bottom:12px}.next-board p{color:#535d65;line-height:1.7}
.closing{padding-block:48px 28px;border-top:1px solid #e5e7e9}.closing-row{display:flex;align-items:center;justify-content:space-between;gap:36px}.closing h2{font-size:32px}.contact{display:flex;flex-wrap:wrap;gap:12px}
.contact a{display:inline-flex;align-items:center;justify-content:center;gap:18px;min-height:46px;padding:12px 20px;background:var(--accent);color:var(--on-accent);border-radius:24px;font-size:14px}.contact a.secondary{background:#edf1f5;color:#2c3a45}
.signature{display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px 24px;font-size:12px;color:#6b7175}.closing-row+.signature{border-top:1px solid #e5e7e9;margin-top:38px;padding-top:24px}

.contrast{background:#fff}.contrast h1,.contrast h2,.contrast h3{font-family:Arial,Helvetica,sans-serif;font-weight:700}.contrast .hero{align-items:center;padding-block:96px 72px;min-height:min(640px,calc(100svh - 190px))}
.contrast .hero:before{background:linear-gradient(180deg,#0b112448,#10182bb0)}.contrast .hero h1{font-size:84px;text-transform:uppercase;max-width:940px}.contrast .hero h1.long-title{font-size:48px}.contrast .eyebrow{display:inline-block;border:1px solid #ffffff80;border-radius:20px;padding:6px 14px;margin-bottom:28px}.contrast .hero-subject{font-size:22px;max-width:640px}.contrast .hero-link{border:0;background:#fff;color:#242628;border-radius:24px;padding:12px 20px;text-shadow:none}.contrast .hero-copy{text-align:left}.contrast .hero-card{background:#fff;color:#202329}.contrast .hero-card span,.contrast .hero-card p{color:#59636d}
.contrast .project-strip{background:#202329;color:#fff;border:0}.contrast .project-facts dt{color:#bbc4ce}
.scope-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.scope-tile{border:1px solid #e2e6ed;border-radius:8px;background:#f3f6fa;padding:32px;display:flex;flex-direction:column;min-width:0;break-inside:avoid}.scope-tile:nth-child(3n+2){background:#f8f2f4}.scope-tile:nth-child(3n){background:#f0f5f2}.tile-top{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:30px}.tile-top .service-type{margin:0}.scope-tile h3{font-size:28px;margin-bottom:22px}.scope-tile .service-price{border-top:1px solid #d6dde4;margin-top:auto;padding-top:24px}.scope-tile .deliverables{margin-bottom:26px}
.contrast .context{background:#21242a;color:#fff;border:0}.contrast .context .section-label{color:#d2ec9e}.contrast .objective-copy{font-family:Arial,Helvetica,sans-serif;font-size:30px;font-weight:400}.contrast .objective-copy.long-copy{font-size:18px}
.contrast .insight-grid article{background:#2c3038;border-color:#4b535d}.contrast .insight-grid p{color:#d7dde3}.contrast .scope-signals{border-color:#4b535d}.contrast .scope-signals strong{color:#fff}.contrast .scope-signals li{border-color:#4b535d;color:#d7dde3}.contrast .scope-signals li span{color:#d2ec9e}
.contrast .investment{background:#23272e;color:#fff;border:0}.contrast .investment .section-label{color:#d2ec9e}.contrast .investment :is(.section-heading>span,.total>span,.total small,.investment-note,th){color:#c6cfd7}.contrast .total{border-top-color:#d2ec9e}.contrast .investment :is(th,td,.price-detail){border-color:#515963}.contrast .schedule{background:#fff}

.compact h1,.compact h2,.compact h3{font-family:Arial,Helvetica,sans-serif}.compact .hero{min-height:min(420px,calc(100svh - 180px));padding-block:72px 40px}.compact .hero h1{font-size:56px;font-weight:650}.compact .hero h1.long-title{font-size:40px}.compact .hero-subject{font-size:20px}.compact .hero-link{display:none}.compact .hero-edition{top:24px}.compact .hero-card{padding:22px}.compact .hero-card strong{font-size:25px}
.compact .section{padding-block:52px}.compact h2{font-size:32px}.compact .section-heading{margin-bottom:28px}.compact .project-facts{padding-block:22px}.compact .investment{background:#fff;border-bottom:1px solid #d8dfe5;border-top:0}.compact .total strong{font-size:34px}.compact .context{background:#f4f6f8;border:0}.compact .objective-copy{font:400 22px/1.6 Arial,sans-serif}.compact .objective-copy.long-copy{font-size:18px}
.scope-ledger{list-style:none;margin:0;padding:0;border-top:2px solid #303b44}.scope-row{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.2fr) minmax(130px,.7fr);gap:26px;padding-block:26px;border-bottom:1px solid #dbe1e6;break-inside:avoid}.scope-name{display:flex;gap:14px;align-items:flex-start;min-width:0}.scope-name .service-number{font:400 14px/1.6 Arial,sans-serif}.scope-name h3{font-size:18px}.scope-row .service-price{text-align:right}.scope-row .service-price strong{font-size:20px}.scope-description{min-width:0}.scope-row .deliverables{font-size:14px}
.scope-name small{display:block;color:#78838c;font-size:11px;margin-top:6px}
.compact .process{grid-template-columns:1fr;gap:0}.compact .process li{display:grid;grid-template-columns:44px minmax(0,1fr);gap:24px;padding-block:22px}.compact .step-number{margin:0}.compact .conditions{gap:32px}

@media(max-width:900px){h1{font-size:56px}h1.long-title{font-size:40px}h2{font-size:36px}.hero{padding-block:80px 44px}.hero-grid{grid-template-columns:1fr;gap:28px}.hero-card{max-width:520px}.hero-subject{font-size:20px}.contrast .hero h1{font-size:58px}.contrast .hero h1.long-title{font-size:40px}.compact .hero h1{font-size:44px}.compact .hero h1.long-title{font-size:34px}.section{padding-block:56px}.objective-copy{font-size:26px}.scope-chapter{gap:28px}.chapter-title{gap:18px}.chapter-title h3{font-size:25px}.scope-tile{padding:24px}.scope-tile h3{font-size:24px}.investment-feature{grid-template-columns:1fr}.investment-feature strong{text-align:left;font-size:36px}.total strong{font-size:34px}.project-facts{grid-template-columns:repeat(2,minmax(0,1fr))}.process{gap:22px}.scope-row{grid-template-columns:1fr 1fr}.scope-row .scope-description{grid-column:1/-1;grid-row:2}.scope-row .service-price{grid-column:2;grid-row:1}.scope-signals{grid-template-columns:1fr}.next-board{grid-template-columns:1fr}.closing-row{align-items:flex-start;flex-direction:column}}
@media(max-width:600px){.wrap{width:88%}.brandbar{min-height:64px;padding-block:14px;gap:16px}.brandbar .brand{font-size:17px;max-width:60%}.brandbar img{width:116px;height:32px}.brandbar nav{font-size:12px;gap:12px}.brandbar nav a:not(:last-child){display:none}h1,.contrast .hero h1,.compact .hero h1{font-size:40px}h1.long-title,.contrast .hero h1.long-title,.compact .hero h1.long-title{font-size:30px}.hero,.contrast .hero,.compact .hero{min-height:min(520px,calc(100svh - 120px));padding-block:76px 36px}.hero-card{padding:20px}.hero-card strong{font-size:25px}.hero-card small{font-size:12px}.eyebrow{font-size:12px;margin-bottom:16px}.hero-subject,.contrast .hero-subject,.compact .hero-subject{font-size:18px;margin-top:16px}.hero-edition{font-size:12px;top:20px}.hero-link{margin-top:22px}.project-facts{gap:18px;padding-block:22px}.project-facts dd{font-size:14px}.section,.compact .section{padding-block:42px}h2,.compact h2{font-size:30px}.section-heading{margin-bottom:28px}.section-heading>span{display:none}.objective-copy,.contrast .objective-copy,.compact .objective-copy{font-size:23px}.objective-copy.long-copy,.contrast .objective-copy.long-copy,.compact .objective-copy.long-copy{font-size:17px}.insight-grid{margin-top:28px}.scope-signals li{grid-template-columns:1fr;gap:4px}.scope-chapter{grid-template-columns:1fr;gap:22px;padding-block:26px}.chapter-title h3{font-size:27px}.chapter-title{gap:18px}.service-number{font-size:34px}.chapter-content{padding-left:0}.service-price strong{font-size:22px}.scope-grid{grid-template-columns:1fr;gap:16px}.scope-tile{padding:24px}.scope-tile h3{font-size:26px}.investment-feature{padding:24px}.investment-feature h3{font-size:28px}.investment-feature strong{font-size:32px}.process{grid-template-columns:1fr;gap:24px}.process li{display:grid;grid-template-columns:44px minmax(0,1fr);gap:20px}.process.method li{display:block}.step-number{margin:0}.process.method .step-number{margin-bottom:16px}.process h3{font-size:18px}.portfolio,.conditions{grid-template-columns:1fr;gap:28px}.totals{gap:26px}.total strong,.compact .total strong{font-size:34px}.scope-row{gap:18px}.scope-name h3{font-size:17px}.scope-row .service-price strong{font-size:18px}.scope-row .service-price>span{font-size:12px}.closing{padding-block:34px 24px}.closing h2{font-size:28px}.contact,.contact a{width:100%}.signature{flex-direction:column;gap:8px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
@media print{@page{size:A4;margin:12mm}body{font-size:10pt}.wrap{width:100%}.brandbar{min-height:40px;padding-block:8px}.brandbar nav,.hero-link,.hero-edition,.contact{display:none}.hero,.contrast .hero,.compact .hero{min-height:72mm;padding-block:20mm 10mm;break-inside:avoid}.hero-copy{width:90%}h1,.hero h1,.contrast .hero h1,.compact .hero h1{font-size:34pt}h1.long-title,.contrast .hero h1.long-title,.compact .hero h1.long-title{font-size:26pt}.hero-subject,.contrast .hero-subject,.compact .hero-subject{font-size:15pt}.project-facts{grid-template-columns:repeat(4,minmax(0,1fr));padding-block:16px}.project-facts dd{font-size:10pt}.section,.compact .section{padding-block:26px}h2,.compact h2{font-size:23pt}.section-heading{margin-bottom:22px}.objective-copy,.contrast .objective-copy,.compact .objective-copy{font-size:17pt}.objective-copy.long-copy{font-size:11pt}.scope-chapter{gap:24px;padding-block:22px}.chapter-title h3,.scope-tile h3{font-size:17pt}.service-number{font-size:26pt}.scope-grid{gap:16px}.scope-tile{padding:18px}.deliverables li{font-size:10pt}.service-price strong{font-size:14pt}.process{grid-template-columns:1fr;gap:16px}.process li{display:grid;grid-template-columns:36px 1fr;gap:16px;padding-top:16px}.step-number{width:36px;height:36px;margin:0}.process h3{font-size:13pt}.portfolio{grid-template-columns:1fr 1fr;gap:18px}.portfolio img{max-height:100mm}.total strong,.compact .total strong{font-size:23pt}.totals{gap:24px}.investment{padding-inline:16px}.price-detail>summary{display:none}.price-detail::details-content{display:block}.table-wrap{overflow:visible}table{font-size:10pt}th,td{padding:10px 6px}thead{display:table-header-group}tr{break-inside:avoid}.scope-row{grid-template-columns:minmax(0,1fr) minmax(0,1.2fr) minmax(90px,.7fr);gap:18px}.scope-row .scope-description{grid-column:auto;grid-row:auto}.scope-row .service-price{grid-column:auto;grid-row:auto}.scope-name h3{font-size:12pt}.scope-row .service-price strong{font-size:12pt}.conditions{gap:24px}.closing{padding-block:24px}.signature{margin-top:0}.closing-row{display:none}h2,h3{break-after:avoid}*{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
`;
